<a href="https://colab.research.google.com/github/panditamey1/nlp_topic_modelling_sentence_transformers_kmeans/blob/main/topic_modelling_sentence_transformers_kmeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer 
from sklearn import metrics

import string
import spacy
np.random.seed(42)

In [3]:
data = pd.read_csv("tweets.csv", engine="python")

In [4]:
data.head()

,username,date,tweet,mentions
0,shivaji_takey,10-06-2020,Please check what happens to this no 940417705...,['vodafonein']
1,sarasberiwala,10-06-2020,Network fluctuations and 4G Speed is pathetic....,['vodafonein']
2,chitreamod,10-06-2020,This has been going on since 3rd... this absol...,['vodafonein']
3,sanjan_suman,10-06-2020,@VodafoneIN I have done my recharge of 555 on...,['vodafonein']
4,t_nihsit,10-06-2020,But when???Still I am not received any call fr...,['vodafonein']

In [ ]:
!pip install transformers

In [ ]:
! pip install sentence-transformers

In [8]:
import torch
from sentence_transformers import SentenceTransformer, util

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [12]:
embeddings = model.encode(data['tweet'])

In [13]:
from sklearn.cluster import KMeans

In [14]:
kmodel = KMeans(n_clusters = 3)

In [15]:
kmodel.fit(embeddings)

KMeans(n_clusters=3)

In [17]:
kmodel.labels_

array([0, 2, 0, ..., 2, 2, 2], dtype=int32)

In [21]:
labels = kmodel.labels_

cluster_sent = {}
for index, label in enumerate(labels):
  if label not in cluster_sent:
    cluster_sent[label] = []
  cluster_sent[label].append(index)

In [23]:
cluster_sent.keys()

dict_keys([0, 2, 1])

In [24]:
cluster1 = data[data.index.isin(cluster_sent[0])]

In [25]:
cluster1

,username,date,tweet,mentions
0,shivaji_takey,10-06-2020,Please check what happens to this no 940417705...,['vodafonein']
2,chitreamod,10-06-2020,This has been going on since 3rd... this absol...,['vodafonein']
6,chitreamod,10-06-2020,"Thanks, but I have visited the website, called...",['vodafonein']
14,mahaprabandhak,10-06-2020,Reverse migration ka zamana hai dear Alu. Kar ...,"['alashshukla', 'airtel_presence', 'relianceji..."
17,krishnavasudev_,10-06-2020,@VodafoneIN à¤à¥à¤¯à¤¾ à¤«à¤¾à¤¯à¤¦à¤¾ à¤¹à¥...,['vodafonein']
...,...,...,...,...
21021,sleepofy,31-05-2020,https://twitter.com/sleepofy/status/126674596...,"['vodafonein', 'akankshanayar17']"
21034,v_manoj19,31-05-2020,Provide me a working customer care number of y...,['vodafonein']
21038,v_manoj19,31-05-2020,@idea_cares unfortunately this is not going in...,"['vodafonein', 'idea_cares']"
21039,ayushhindia,31-05-2020,Haven't got any surprise? ðð Moreover ha...,['vodafonein']
21042,mvjdobhal,31-05-2020,I sent u my contact no. But still did not get ...,['vodafonein']

In [26]:
cluster2 = data[data.index.isin(cluster_sent[1])]

In [27]:
cluster2

,username,date,tweet,mentions
3,sanjan_suman,10-06-2020,@VodafoneIN I have done my recharge of 555 on...,['vodafonein']
4,t_nihsit,10-06-2020,But when???Still I am not received any call fr...,['vodafonein']
10,mailgurvinder,10-06-2020,@VodafoneIN @VodafoneGroup @TRAI Why the hell ...,"['vodafonein', 'vodafonegroup', 'trai']"
16,isrinivasbjp,10-06-2020,"Worst customer care, I charged 1072 for intern...","['vodafonein', 'jiocare']"
32,kanikadewanpfa,10-06-2020,@VodafoneIN such a sorry state of affairs . Yo...,"['vodafonein', 'sapagalu']"
...,...,...,...,...
21026,amimulehsaan,31-05-2020,I too am getting these message since December ...,"['suyi', 'vodafonein']"
21027,riakapo81750186,31-05-2020,What is the point of recharging when you don't...,['vodafonein']
21029,rushilyahoo,31-05-2020,"Also in my previous tweet, i have mentioned th...",['vodafonein']
21035,muneshtyagi20,31-05-2020,@VodafoneIN \nI am using 9953992234 since ten ...,['vodafonein']
21041,tanzee2002,31-05-2020,@VodafoneIN Sorry to say but you was kidding m...,['vodafonein']

In [28]:
cluster3 = data[data.index.isin(cluster_sent[2])]

In [29]:
cluster3

,username,date,tweet,mentions
1,sarasberiwala,10-06-2020,Network fluctuations and 4G Speed is pathetic....,['vodafonein']
5,tanzeelu3,10-06-2020,@VodafoneIN mere area me vodafone ka network n...,['vodafonein']
7,mayankpatel7293,10-06-2020,"@VodafoneIN @VodafoneGroup\nHi,\n Today my Vod...","['vodafonein', 'vodafonegroup', 'trai', 'trai_..."
8,deeranjith,10-06-2020,"Dear Vodafone, I have already responded to you...",['vodafonein']
9,govindrathi799,10-06-2020,@VodafoneIN SIR OUR MARKET AREA ME BILKUL NETW...,['vodafonein']
...,...,...,...,...
21040,citiznnarayan,31-05-2020,@VodafoneIN Please check DM i have sent the nu...,['vodafonein']
21043,valleyofpeace2,31-05-2020,dear @VodafoneIN i have bn facing ur network ...,['vodafonein']
21044,mushtabaarshad,31-05-2020,rubbish i made many time @VodafoneIN you didn...,['vodafonein']
21045,gouravgv,31-05-2020,Why the caller tunes sound so horrible? if a s...,"['airtelindia', 'idea', 'vodafonein', 'bsnlcor..."
21046,v_manoj19,31-05-2020,@VodafoneIN @idea_cares what nonsense are u gu...,"['vodafonein', 'idea_cares']"

In [31]:
cluster1.to_csv("cluster_sentence_transformers_1.csv", index = False)
cluster2.to_csv("cluster_sentence_transformers_2.csv", index = False)
cluster3.to_csv("cluster_sentence_transformers_3.csv", index = False)